### ISSUE TITLE
Planned Features/Roadmap

### ISSUE THREAD

**Issue by gorgobacka** [thePurpleMonkey/sheet-music-organizer#1]
This seems to be a very interesting project. I'm looking for something like this to organize my digital sheet music (single songs and songbooks) for a while already.

I know that your project is at an very early stage. But what features do you have in mind and are planning to implement?

**Comment by thePurpleMonkey** [comment]
Hi, thanks for your interest in this project! I haven't checked my GitHub in a while, so sorry I didn't responded to your issue right away.

You can actually view a live version of this website at https://smo.michaelhumphrey.dev. You can read more about the website on the front page there, but here's a quick rundown of the features:
 - Manage multiple collections of sheet music
 - Organize songs with tags
 - Collaborate with other users
 - Plan and share performances with setlists
 - Search for songs with a variety of filters
 - Responsive design for mobile

**Comment by gorgobacka** [comment]
Thank you for your response.

Are you going to include files (e.g. pdf) that represent the songs/books also? It would be great to organize and to view the sheets within **one**  website.

**Comment by thePurpleMonkey** [comment]
No, the website does not support hosting files at this time. It does allow linking to files hosted on other platforms like Dropbox, Google Drive, or OneDrive. It can also just note the physical location of sheet music, like what binder it's in. The goal is to empower the user to catalog and organize their sheet music library as it already is.
